### ISSUE TITLE
sox in linuxbrew

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/audiorecorder#24]
Looks like when installing audiorecorder via linuxbrew, the sox dependency does not end up configured to use the default alsa device.  If sox is installed via apt install there is no problem.  Probably some path issue that needs looking into!

**Comment by retokromer** [comment]
Did you [set the global variables](https://avpres.net/FFmpeg/install_Linux.html), usually in `.bashrc`, at installation?

**Comment by privatezero** [comment]
aha! I might have neglected that step.  I'll test it out when I get back home!

**Comment by retokromer** [comment]
Sorry, I cannot test myself now, but if it still gives an error, then you could file an issue to [Linuxbrew](https://github.com/Linuxbrew).

**Comment by privatezero** [comment]
I have confirmed that the error still occurs for the sox install when linuxbrew is on the PATH - I'll keep looking into this, but in the meantime the apt install makes things hunky dory (at least in respect to running- I don't have a linux compatible A/D so can't test quality)

**Comment by retokromer** [comment]
I’ll try to test on Saturday.

**Comment by privatezero** [comment]
Thank you much! Have you been able to successfully get ffplay to work via linuxbrew as well?  I seem to be running into a similar issue - if I build FFmpeg via apt-get (using a PPA for a newer version) ffplay runs, but built via linuxbrew it throws an error 

> Could not initialize SDL - No available video device

Would love to figure out a way to get the install formula working so that users wouldn't have to manually install the dependencies using apt-get!

**Comment by privatezero** [comment]
oh haha! looks like the linuxbrew version of sdl2 was conflicting with the other installed version- I was able to fix the ffplay issue at least by forcing brew to uninstall its version of sdl2!

**Comment by privatezero** [comment]
Yay! That gave me the idea to try manually installing alsa via brew instead of using the system install version. Looks like that solved the sox alsa issue!

**Comment by retokromer** [comment]
Hello @privatezero, @pjotrek-b mentioned yesterday on twitter [Zenity](http://www.linux.org/threads/zenity-gui-for-shell-scripts.5567/), GUI for shell scripts, which could be interesting indeed for many of our projects!

**Comment by retokromer** [comment]
Update: There are some issues with Zenity too…

**Comment by privatezero** [comment]
Hi! Yes, I have experimented with Zenity before and found it interesting, but problematic.  The biggest problem I had (in macOS at least) was it would often open its window behind existing windows, which could be very confusing for users!

**Comment by retokromer** [comment]
Yes, that’s also one of my cons. There are other solutions I’m testing, including a fork from Zenity. No one I would suggest so far… :-(

**Comment by pjotrek-b** [comment]
Regarding focus-stealing issues with Zenity:
Maybe "[wmctrl](https://en.wikipedia.org/wiki/Wmctrl)" could be used to stabilize it's behavior (for starters) - and for long-term: Fix/improve Zenity?
(Don't know if wmctrl exists/works on MacOS though)

**Comment by retokromer** [comment]
Hmm… I really don’t have the time to fix Zenity ;-)

Thank you for the information! I’ll check it.

**Comment by privatezero** [comment]
I seem to recall that the linux workarounds didn't exist in macOS, but it has been a while since I looked into it so I could be totally wrong about that!

**Comment by pjotrek-b** [comment]
@retokromer:
Didn't mean that **you** should fix Zenity.

Just tried not to promote a workaround without mentioning that it might be possible to actually fix things: Because it's FOSS :smile:

**Comment by retokromer** [comment]
@pjotrek-b Нема проблема! My answer was meant ironically, therefore the added ;-)

**Comment by retokromer** [comment]
The installation seems to be resolved in https://github.com/amiaopensource/audiorecorder/pull/32.

**Comment by privatezero** [comment]
As @retokromer says! Resolved for now via https://github.com/amiaopensource/audiorecorder/pull/32. Closing!
