### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/audiorecorder#28]
Hi all! As some (but not all) of my work was undertaken during my 'professional development' time of my NDSR residency, and as CUNY-TV signed a contract with the AAPB that works created by residents during 'professional development time' would be released under a CC-BY-4.0 license, that is the license that I originally applied to this entire repository.

I have contacted the AAPB, and received permission to change the license governing the script to a more OSS specific license while leaving the documentation covered by the original CC-BY-4.0.

I favor applying the [BSD 3-Clause License](https://opensource.org/licenses/BSD-3-Clause) to the audiorecorder script; I would like to know what contributors think about this, and if they would be ok with this change!

**Comment by retokromer** [comment]
Ha! That licence remembers me the [one I wrote](https://retokromer.ch/publications/FilmXML.html#ch13) many years ago… Today I prefer CC-BY, but **I’m very fine with BSD.**

**Comment by todrobbins** [comment]
BSD be cool

**Comment by privatezero** [comment]
Cool! I'll go ahead and make the change then!

**Comment by privatezero** [comment]
Updated in https://github.com/amiaopensource/audiorecorder/commit/f14fad6cd2f780a395b63dda77330af85480cd34
