### ISSUE TITLE
passthrough directory problem

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/audiorecorder#41]
`audiorecorder -p` will ask for a target directory if none is provided. This should be fixed as is unnecessary and could be confusing to users.

**Comment by retokromer** [comment]
Is this the same as #40?

**Comment by privatezero** [comment]
github was having some hiccups and creating 404 errors for issue creation, so this was created twice! So yes - same as https://github.com/amiaopensource/audiorecorder/issues/40. Closing!
