### ISSUE TITLE
macOS file paths

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/audiorecorder#70]
As we are now at almost full functionality in the linux branch, seems like a good time to fix the paths and make this functional in macOS! I would prefer to find a way that minimizes hard coding file paths, and doesn't require user input (like how Audacity requires the input of FFmpeg path) but maybe setting this up with a hard coded path to homebrew and using brew commands to locate paths to dependencies is a way to do this? Thoughts?

**Comment by retokromer** [comment]
Yes, I plenty agree: it should be possible to populate the path variable on-the-fly, which is a much more elegant way (and a general one as well) to implement – at least to my taste.

**Comment by privatezero** [comment]
Closing for now - needs a more elegant solution, but paths are operational for now.
