### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/audiorecorder#89]
Is a new release planned soon? The current one is from 17<sup>th</sup> of August and 21 commits behind  the master.

**Comment by privatezero** [comment]
Oh yes, that is a very good point! I'll run a couple tests over the next couple days and look into making an actual release next week!

**Comment by retokromer** [comment]
Resolved in https://github.com/amiaopensource/audiorecorder/releases/tag/2019-05-21, thank you!
